version: "3"
services:
  broker:
    build: broker
    ports:
      - "8080:8080"
  auldfellas:
    build: auldfellas
    container_name: auldfellas
    depends_on:
      - broker
    ports:
      - "8083:8083"
  girlpower:
    build: girlpower
    container_name: girlpower
    depends_on:
      - broker
    ports:
      - "8082:8082"
  dodgydrivers:
    build: dodgydrivers
    container_name: dodgydrivers
    depends_on:
      - broker
    ports:
      - "8081:8081"